defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: journal_development
  host: localhost
  <<: *defaults

test:
  database: journal_test
  host: localhost
  min_messages: WARNING
  <<: *defaults

production:
  database: journal_production
  <<: *defaults